#!/bin/bash
set -ex

for version in 2.6 2.7 2.8 2.9; do
    docker image build \
        --build-arg "version=$version.0" \
        --tag "$DOCKER_REPO:$version" \
        .

    docker image build \
        --build-arg "version=$version.0" \
        --tag "$DOCKER_REPO:$version-bionic" \
        -f bionic/Dockerfile \
        .
done


